version: 2
project_name: xmigrator
dist: .artifacts/release

before:
  hooks:
    - go run tools/dev.go workspace

builds:
  - id: xmigrator
    dir: cmd/xmigrator
    main: .
    binary: xmigrator
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ if .IsSnapshot }}{{ .Version }}{{ else }}{{ .Tag }}{{ end }}

archives:
  - ids: [xmigrator]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - docs/*.md

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  github:
    owner: sxwebdev
    name: xmigrator
  name_template: '{{ .Tag }}'
  prerelease: false
